### ISSUE TITLE
No Longer Working

### ISSUE THREAD

**Issue by Justin-Lund** [Sv3n/ktane-hue#1]
Unfortunately, this no longer seems to work :(
The explode test works, but once the game loads up, nothing happens / there doesn't seem to be any more interaction between the game & hue.

I assume it's not just me, given that this mod is fairly old.

I know there's probably not (m)any other people still using this, but any plans to come back to it / update it?
I used to really love playing this game with this mod!

**Comment by Sv3n** [comment]
Hi! Just tried it out, and it indeed failed for multiple reasons. I suspect the logging of the game got updated w.r.t. when I first made this. I also discovered things did not work if the computer has DST enabled.

I've patched things up to the point where it works again when I test it here locally. The latest commit on master (c0853a4a) has these fixes. If problems persist, then we should look at it further, otherwise: have fun! :)

**Comment by Justin-Lund** [comment]
@Sv3n Hi, thanks so much for the quick response and fix, I really appreciate it!
It's working great now! The only thing still not working properly for me is the triggering of in_game_quick when there's one minute left.

The code for getting the light to flash red is still working properly, as I get the red lights when I hit 2 strikes, but I don't get the red lights when the timer hits 1 minute - presumably another change to the logging.

I see that it does still output the line "Executing random action of type OneMinuteLeft", which your code is looking for, but I also noticed that it's listed under 'DEBUG' in the log - not sure if that was previously 'INFO' & if that's making the difference, or if it's something else

**Comment by Sv3n** [comment]
I suspect the source of that line changed from `Assets.Scripts.Pacing.PaceMaker` to `PaceMaker`. I added `PaceMaker` as an event source to look for in the script in the most recent commit. That probably fixes it, but I have not had time to test it yet.

**Comment by Justin-Lund** [comment]
Legend! That did it! Thanks again!!
